architecture: replication
replicaCount: 2
auth:
  database: mydb
  username: myuser
  existingSecret: mysql-creds

primary:
  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi


secondary:
  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi


global:
  security:
    allowInsecureImages: True
image: 
  registry: docker.io
  tag: latest
  repository: bitnamilegacy/mysql