apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-app
  namespace: fargate
  labels:
    app: company-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: company-app
  template:
    metadata:
      labels:
        app: company-app
    spec:
      imagePullSecrets:
      - name: docker-creds
      containers:
      - name: company-app
        image: michael101/java-maven-app:company-app-1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: companyapp-configmap
                key: DB_USER
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-password
          - name: DB_NAME
            valueFrom:
              configMapKeyRef: 
                name: companyapp-configmap
                key: DB_NAME
          - name: DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: companyapp-configmap
                key: DB_SERVER 
          

---

apiVersion: v1
kind: Service
metadata:
  name: companyapp-service
spec:
  type: LoadBalancer
  selector:
    app: company-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
        
