apiVersion: v1
kind: ConfigMap
metadata:
  name: companyapp-configmap
  namespace: fargate
data:
  PMA_HOST: mysql-release-primary.default.svc.cluster.local
  PMA_PORT: "3306"
  DB_USER: myuser
  DB_NAME: mydb
  DB_SERVER: mysql-release-primary.default.svc.cluster.local